<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Todo.Infrastructure</RootNamespace>
		<AssemblyName>Todo.Infrastructure</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Todo.Application\Todo.Application.csproj" />
	</ItemGroup>

</Project>
