@Web_HostAddress = https://localhost:7135
@Email=admin@localhost
@Password=Administrator1!

# POST Register
POST {{Web_HostAddress}}/register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Login
# @name login
POST {{Web_HostAddress}}/login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/todo/lists
Authorization: Bearer {{login.response.body.$.accessToken}}

###

# GET TodoList
GET {{Web_HostAddress}}/api/todo/lists/1
Authorization: Bearer {{login.response.body.$.accessToken}}

###

# POST TodoList
POST {{Web_HostAddress}}/api/todo/lists
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "Title": "Backlog"
}

###

# PUT TodoList
PUT {{Web_HostAddress}}/api/todo/lists/1
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoList
DELETE {{Web_HostAddress}}/api/todo/lists/1
Authorization: Bearer {{login.response.body.$.accessToken}}

###

# POST TodoItem
POST {{Web_HostAddress}}/api/todo/items
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

# PUT TodoItem
PUT {{Web_HostAddress}}/api/todo/items/1
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/todo/items/1
Authorization: Bearer {{login.response.body.$.accessToken}}

###
