<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Todo.Domain</RootNamespace>
    <AssemblyName>Todo.Domain</AssemblyName>
  </PropertyGroup>
  
</Project>
